export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  FOUNDER: '/founder',
  DESIGN_PHILOSOPHY: '/design-philosophy',
  BRAND_PROMISE: '/brand-promise',
  QUALITY_ASSURANCE: '/quality-assurance',
  CUSTOMER_FEEDBACK: '/customer-feedback',
  CONTACT: '/contact',
  SUPPORT: '/support',
  BLOG: '/blog',
  FAQ: '/faq',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  MEMBER_BENEFITS: '/member-benefits',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  ACCOUNT: '/account',
  ORDERS: '/orders',
  FAVORITES: '/favorites',
  ORDER_QUERY: '/order',
  ORDER_CONFIRM: '/order-confirm/:orderId',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:slug',
  MAIN_FOOD: '/main-food',
  SNACKS: '/snacks',
  HEALTH: '/health',
  JOINTS: '/joints',
  REGISTER_PRODUCT: '/register-product',
  NOT_FOUND: '*',
};

export default ROUTES;
